### ISSUE TITLE
RuntimeWarning: coroutine 'ChatGPT.chat' was never awaited

### ISSUE THREAD

**Issue by minaremeli** [spcl/CheckEmbed#8]
I got a `RuntimeWarning: coroutine 'ChatGPT.chat' was never awaited` for the following line:
https://github.com/spcl/CheckEmbed/blob/707aa71568552723ea962122b692b4b88d83be17/CheckEmbed/language_models/chatgpt.py#L112

Got the same warning for `'EmbeddingGPT.embed_query'` as well.

I suspect that changes made in https://github.com/spcl/CheckEmbed/commit/542708ca602aad8737459f841561c0541e4edf01 may have broken async queries to the OpenAI API. Reverting to the commit before that fixed my issue.

**Comment by LorenzoPaleari** [comment]
Thank you for reporting the error.
We are working on some updates to the code base, which are also going to fix the Issue.

To temporarily solve the issue you can simply change from AsyncOpenAI to OpenAI and remove the async/await from chat function. The async operator was left while using Asyncio, but we switched to multithreading and it is no longer necessary.
(Same apply for EmbeddingGPT)

https://github.com/spcl/CheckEmbed/blob/feef0f720c5e0485eabb8637f77d5721f92b7237/CheckEmbed/language_models/chatgpt.py#L18
https://github.com/spcl/CheckEmbed/blob/feef0f720c5e0485eabb8637f77d5721f92b7237/CheckEmbed/language_models/chatgpt.py#L70
https://github.com/spcl/CheckEmbed/blob/feef0f720c5e0485eabb8637f77d5721f92b7237/CheckEmbed/language_models/chatgpt.py#L129
https://github.com/spcl/CheckEmbed/blob/feef0f720c5e0485eabb8637f77d5721f92b7237/CheckEmbed/language_models/chatgpt.py#L141

**Comment by rgersten** [comment]
Thank you again for reporting the issue.

The changes that we just pushed to the main branch should address the problem.
